### ISSUE TITLE
Update mpv.net

### ISSUE THREAD

**Issue by Witchilich** [C4illin/Choco-Packages#2] opened 2019-11-12 09:30 UTC
Are you gonna update mpv.net or is it going to forever be stuck in version 5.4.2 ?

**Comment by C4illin** [comment] 2019-11-12 14:06
5.4.3 has been out for awhile [https://chocolatey.org/packages/mpvnet.install/5.4.3.0](https://chocolatey.org/packages/mpvnet.install/5.4.3.0). The problem is that the moderation process is just taking some time.

Run `choco upgrade mpvnet.install --version=5.4.3.0` to install it.

**Comment by Witchilich** [comment] 2019-11-18 15:15
Maybe there is some issue with 5.4.3. Try updating to 5.4.4.0 now.

**Comment by C4illin** [comment] 2019-11-18 22:04
The problem is that the moderation queue is really long, and because the package is still pending moderation I will need to update it manually.

Edit:
The manual update failed since the last version is still pending approval, will try to fix it in another way.

**Comment by C4illin** [comment] 2019-11-19 16:02
Actually it is a bug on chocolatey. https://github.com/chocolatey/chocolatey.org/issues/613 

It seems that I will have to wait for a server restart, which means the release will be delayed.

**Comment by Witchilich** [comment] 2019-11-19 16:07
By the way, why didn't you just call it `choco install mpv.net` ?

**Comment by C4illin** [comment] 2019-11-19 16:09
Because there is a portable version available (that isn't on chocolatey) and I want it to be compatible with that if anyone want to add the portable version to chocolatey.

**Comment by Witchilich** [comment] 2019-11-22 13:05
So, what happened to the icon ?
Also, hope we receive the 5.4.4.0 update.

**Comment by C4illin** [comment] 2019-11-22 17:35
The icon cdn seems to be a bit unstable so it's now changed. Thanks for the notice!

I also hope the we receive the 5.4.4.0 update soon, I have been trying to push it for days now without any success.

**Comment by C4illin** [comment] 2020-08-10 14:45
@Witchilich Why did you close it?

**Comment by Witchilich** [comment] 2020-08-11 10:27
I thought you were not working on it, since it has not been updated in a while.

**Comment by gep13** [comment] 2020-08-19 12:30
@C4illin hi, I am a member of the Chocolatey Team, and I noticed that you have been trying to push a new package version for mpvnet.install, and that this has been failing.  You may not see this error returned to the choco.exe (there is an open issue this here https://github.com/chocolatey/chocolatey.org/issues/884), but on the server side, the error that is being reported is:

```
A nuget package's Description property may not be more than 4000 characters long.
```

In order to successfully push the chocolatey package, you will need to reduce the number of characters within the description field.

Please let me know if you have any questions.

**Comment by C4illin** [comment] 2020-08-26 21:26
@gep13 Thanks for this information! :)
It turns out the description was just 75 characters over the limit so I trimmed it down a bit.

Thank you!

**Closed as completed by C4illin** 2020-08-26 21:26 UTC

**Comment by sebma** [comment] 2021-11-16 22:47
https://github.com/stax76/mpv.net/issues/296#issuecomment-970754319
